# Alternative NodePort service for NGINX (for minikube compatibility)
# This can be used instead of or alongside the Ingress resource
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-nodeport
  namespace: default
spec:
  selector:
    app: nginx-proxy
  type: NodePort
  ports:
    - port: 443
      targetPort: 443
      nodePort: 30443
      protocol: TCP
      name: https

